package com.orthowatch.controller;

import com.orthowatch.dto.AlertAcknowledgeResponse;
import com.orthowatch.dto.AlertResolveRequest;
import com.orthowatch.dto.AlertResolveResponse;
import com.orthowatch.model.Alert;
import com.orthowatch.model.User;
import com.orthowatch.repository.UserRepository;
import com.orthowatch.service.AlertService;
import jakarta.validation.Valid;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.*;

/**
 * REST controller for alert lifecycle management.
 *
 * <p>Provides endpoints for clinicians to acknowledge and resolve alerts generated by the risk
 * engine and scheduled tasks.
 */
@RestController
@RequestMapping("/api/v1/alerts")
@RequiredArgsConstructor
public class AlertController {

  private final AlertService alertService;
  private final UserRepository userRepository;

  /**
   * Acknowledge a PENDING alert.
   *
   * @param alertId the alert UUID
   * @return acknowledgement confirmation with timestamp
   */
  @PostMapping("/{alertId}/acknowledge")
  @PreAuthorize("hasAnyRole('SURGEON', 'NURSE')")
  public ResponseEntity<AlertAcknowledgeResponse> acknowledge(@PathVariable UUID alertId) {
    User currentUser = getCurrentUser();
    Alert alert = alertService.acknowledge(alertId, currentUser);

    AlertAcknowledgeResponse response =
        AlertAcknowledgeResponse.builder()
            .alertId(alert.getId())
            .status(alert.getStatus())
            .acknowledgedAt(alert.getAcknowledgedAt())
            .build();

    return ResponseEntity.ok(response);
  }

  /**
   * Resolve an ACKNOWLEDGED alert with an escalation outcome.
   *
   * @param alertId the alert UUID
   * @param request the resolve request containing outcome and optional notes
   * @return resolution confirmation with outcome and timestamp
   */
  @PostMapping("/{alertId}/resolve")
  @PreAuthorize("hasAnyRole('SURGEON', 'NURSE')")
  public ResponseEntity<AlertResolveResponse> resolve(
      @PathVariable UUID alertId, @Valid @RequestBody AlertResolveRequest request) {
    User currentUser = getCurrentUser();
    Alert alert = alertService.resolve(alertId, request, currentUser);

    AlertResolveResponse response =
        AlertResolveResponse.builder()
            .alertId(alert.getId())
            .status(alert.getStatus())
            .escalationOutcome(alert.getEscalationOutcome())
            .resolvedAt(alert.getResolvedAt())
            .build();

    return ResponseEntity.ok(response);
  }

  private User getCurrentUser() {
    Authentication auth = SecurityContextHolder.getContext().getAuthentication();
    String email = auth.getName();
    return userRepository
        .findByEmail(email)
        .orElseThrow(() -> new IllegalStateException("Authenticated user not found in database"));
  }
}
